# Hexo é…ç½®æ–‡ä»¶
nav:
  logo: /favicon.ico
  display_title: true
  fixed: false # fixed navigation bar

# ç½‘ç«™
default_top_img: /static/images/é»˜è®¤èƒŒæ™¯.jpg
favicon: /favicon.ico

# ç¤¾äº¤å›¾æ ‡
social:
  fab fa-github: https://github.com/YangRucheng || Github
  fab fa-qq: https://qm.qq.com/q/rtZpWJIgPQ || QQ
  fab fa-bilibili: https://space.bilibili.com/472876342 || å“”å“©å“”å“©
  fab fa-house: https://misaka-network.top || å¾¡å‚ç½‘ç»œå·¥ä½œå®¤
  fas fa-envelope: mailto:admin@yangrucheng.top || Email

# å¤´åƒ
avatar:
  img: https://avatars.githubusercontent.com/u/60175467?v=4
  effect: true

# ä¾§è¾¹æ 
aside:
  enable: true
  hide: false
  button: true
  mobile: true
  position: right
  card_author:
    enable: true
    description:
    button:
      enable: true
      icon: fab fa-github
      text: å…³æ³¨æˆ‘çš„GitHub
      link: https://github.com/YangRucheng
  card_announcement:
    enable: true
    content: æ¬¢è¿æ¥åˆ°æˆ‘çš„å°ç«™ğŸ‘ğŸ»
# èœå•
menu:
  é¦–é¡µ: / || fa fa-home
  æ—¶é—´è½´: /archives/ || fa fa-archive
  æ ‡ç­¾: /tags/ || fa fa-tags
  åˆ†ç±»: /categories/ || fa fa-folder-open
  å‹é“¾: /link/ || fa fa-link

# å³ä¸‹è§’æŒ‰é’®
darkmode:
  enable: true
  button: true
  autoChangeMode: 1
rightside_scroll_percent: true

# å°é¢
cover:
  index_enable: true
  aside_enable: true
  archives_enable: true
  default_cover: https://api.anosu.top/img/?sort=furry

# è¯„è®º
# Giscus https://giscus.app/
giscus:
  repo: "YangRucheng/Blog-Hexo"
  repo_id: "R_kgDOI4-j6Q"
  category_id: "DIC_kwDOI4-j6c4CUaSX"
  theme:
    light: light
    dark: dark

# é¡µè„šå†…å®¹
custom_text: <a href="icpé“¾æ¥"><img class="icp-icon" src="icpå›¾ç‰‡"><span>å¤‡æ¡ˆå·ï¼š1xxxxx</span></a>
